---
- name: Install and Configure Apache Tomcat 10
  hosts: all
  become: yes
  vars:
    tomcat_version: "10.1.28"
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    install_dir: "/opt/tomcat"
    java_package: "openjdk-11-jdk"  # You can adjust this for your preferred Java version
  tasks:

    # 1. Install Java
    - name: Install Java
      apt:
        name: "{{ java_package }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Java (for RHEL-based systems)
      yum:
        name: "java-11-openjdk-devel"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    # 2. Create Tomcat User and Group
    - name: Create a group for Tomcat
      group:
        name: "{{ tomcat_group }}"

    - name: Create a user for Tomcat
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        shell: /bin/false

    # 3. Download and Install Tomcat
    - name: Download Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Create Tomcat Installation Directory
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ install_dir }}"
        remote_src: yes
        creates: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Change ownership of Tomcat directory
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes

    - name: Backup the existing tomcat-users.xml file
      copy:
        src: /etc/tomcat9/tomcat-users.xml
        dest: /etc/tomcat9/tomcat-users.xml.bak
        remote_src: yes
        backup: yes



    - name: Add manager roles and users to tomcat-users.xml
       blockinfile:
        path: /etc/tomcat9/tomcat-users.xml
        insertafter: "</tomcat-users>"
        block: |
          <!-- Role for Tomcat Manager -->
          <role rolename="manager-gui"/>
          <role rolename="manager-script"/>
          <role rolename="manager-jmx"/>
          <role rolename="manager-status"/>

          <!-- Define users with manager roles -->
          <user username="admin" password="admin" roles="manager-gui,manager-script,manager-jmx,manager-status"/>

    # 4. Configure Tomcat Service
    - name: Create systemd service file for Tomcat
      copy:
        content: |
          [Unit]
          Description=Apache Tomcat 10 Servlet Container
          After=network.target

          [Service]
          Type=forking
          
          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          Environment=CATALINA_PID={{ install_dir }}/apache-tomcat-{{ tomcat_version }}/temp/tomcat.pid
          Environment=CATALINA_HOME={{ install_dir }}/apache-tomcat-{{ tomcat_version }}
          Environment=CATALINA_BASE={{ install_dir }}/apache-tomcat-{{ tomcat_version }}
          ExecStart={{ install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/startup.sh
          ExecStop={{ install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/tomcat.service
        mode: '0644'

    # 5. Start and Enable Tomcat Service
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started

    - name: Enable Tomcat service at boot
      systemd:
        name: tomcat
        enabled: yes
